{% set version = '1.2-3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-seriation
  version: {{ version|replace("-", "_") }}

source:
  fn: seriation_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/seriation_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/seriation/seriation_{{ version }}.tar.gz
  sha256: 22cd0bc3988883b3689cdc9642ac36f25db1c13012b0063c5944082e21e1d0e0

build:
  merge_build_host: True  # [win]
  number: 1001
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-tsp
    - r-cluster
    - r-colorspace
    - r-dendextend
    - r-gclus
    - r-gplots
    - r-qap
    - r-registry
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass
    - r-tsp
    - r-cluster
    - r-colorspace
    - r-dendextend
    - r-gclus
    - r-gplots
    - r-qap
    - r-registry

test:
  commands:
    - $R -e "library('seriation')"           # [not win]
    - "\"%R%\" -e \"library('seriation')\""  # [win]

about:
  home: http://lyle.smu.edu/IDA/seriation
  license: GPL-3
  summary: Infrastructure for seriation with an implementation of several seriation/sequencing
    techniques to reorder matrices, dissimilarity matrices, and dendrograms. Also provides
    (optimally) reordered heatmaps, color images and clustering visualizations like
    dissimilarity plots, and visual assessment of cluster tendency plots (VAT and iVAT).
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
