{% set version = "1.5.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-seriation
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/seriation_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/seriation/seriation_{{ version }}.tar.gz
  sha256: 6c1a597f961a1eaeea26d2bb01f6b136622270e50ca48dc4f1b6cd3a26c42855

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-mass                       # [build_platform != target_platform]
    - r-tsp                        # [build_platform != target_platform]
    - r-ca                         # [build_platform != target_platform]
    - r-cluster                    # [build_platform != target_platform]
    - r-colorspace                 # [build_platform != target_platform]
    - r-foreach                    # [build_platform != target_platform]
    - r-gclus                      # [build_platform != target_platform]
    - r-qap                        # [build_platform != target_platform]
    - r-registry                   # [build_platform != target_platform]
    - r-vegan                      # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-tsp
    - r-ca
    - r-cluster
    - r-colorspace
    - r-foreach
    - r-gclus
    - r-qap
    - r-registry
    - r-vegan
  run:
    - r-base
    - r-mass
    - r-tsp
    - r-ca
    - r-cluster
    - r-colorspace
    - r-foreach
    - r-gclus
    - r-qap
    - r-registry
    - r-vegan

test:
  commands:
    - $R -e "library('seriation')"           # [not win]
    - "\"%R%\" -e \"library('seriation')\""  # [win]

about:
  home: https://github.com/mhahsler/seriation
  license: GPL-3.0-only
  summary: Infrastructure for ordering objects with an implementation of several seriation/sequencing/ordination techniques to reorder matrices, dissimilarity matrices, and dendrograms. Also provides (optimally) reordered heatmaps, color images and clustering visualizations like dissimilarity plots, and visual assessment
    of cluster tendency plots (VAT and iVAT).
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
