{% set version = "1.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-seriation
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/seriation_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/seriation/seriation_{{ version }}.tar.gz
  sha256: bd321f44ab94953dfc80e1f8609f8c04cecc91d35b2414d8ad4d4acd53298dad

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
  host:
    - r-base
    - r-ca
    - r-cluster
    - r-colorspace
    - r-gclus
    - r-mass
    - r-qap
    - r-registry
    - r-tsp
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-ca
    - r-cluster
    - r-colorspace
    - r-gclus
    - r-mass
    - r-qap
    - r-registry
    - r-tsp

test:
  commands:
    - $R -e "library('seriation')"           # [not win]
    - "\"%R%\" -e \"library('seriation')\""  # [win]

about:
  home: https://github.com/mhahsler/seriation
  license: GPL-3.0-only
  summary: Infrastructure for ordering objects with an implementation of several seriation/sequencing/ordination techniques to reorder matrices, dissimilarity matrices, and dendrograms. Also provides (optimally) reordered heatmaps, color images and clustering visualizations like dissimilarity plots, and visual assessment
    of cluster tendency plots (VAT and iVAT).
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
